server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: backend-comic

  datasource:
    url: jdbc:mysql://localhost:3307/webtoon
    username: webtoon
    password: 12345Webtoon
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.zeptomail.com
    port: 587
    username: emailapikey
    password: wSsVR61z+RDwC6t8zjatJe84n1xcA1inFB98jQf07nT1HKjLpsdtxBbKAQbzSvMcGWRvQmcTp+ohmB8A22EJ29Qvm19UDyiF9mqRe1U4J3x17qnvhDzIWWlckBCILYwMxwlrnmJiFMEn+g==
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
          from: noreply@kimthi1708.id.vn
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    protocol: smtp
    default-encoding: UTF-8

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# Cấu hình CORS
app:
  frontend-url: http://localhost:3000
  cors:
    allowed-origins: http://localhost:3000
  verification-token-expiration: 1800000 # 30p
  forgot-password-token-expiration: 1800000 # 30p

crawler:
  otruyen:
    api-url: https://otruyenapi.com/v1/api/danh-sach/truyen-moi?page=
    api-comic-detail: https://otruyenapi.com/v1/api/truyen-tranh/
    image-cdn: https://img.otruyenapi.com
  request:
    delay-ms: 0
  batch:
    size: 5
    delay-ms: 0

jwt:
  expiration: 3600000 # 1 giờ
  refresh-expiration: 604800000 # 7 ngày

b2:
  accessKeyId: 00578cb19b5269e0000000002
  secretKey: K005p7EbGqGkvr3NSYf5JApC8gQdc9U
  endpoint: https://s3.us-east-005.backblazeb2.com
  region: us-east-005
  bucketName: webtoon-thjvjpxx
