server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: backend-comic
  datasource:
    url: jdbc:mysql://localhost:3306/webtoon
    username: webtoon
    password: 12345Webtoon
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Cấu hình CORS
app:
  cors:
    allowed-origins: http://localhost:3000

google-drive:
  folder-id: 1H89l7BIVVNR3byETuuqZp2OXJpbSsT2R

