server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: backend-comic
  datasource:
    url: jdbc:mysql://localhost:3307/webtoon
    username: webtoon
    password: 12345Webtoon
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# Cấu hình CORS
app:
  cors:
    allowed-origins: http://localhost:3000

crawler:
  otruyen:
    api-url: https://otruyenapi.com/v1/api/danh-sach/truyen-moi?page=
    api-comic-detail: https://otruyenapi.com/v1/api/truyen-tranh/
    image-cdn: https://img.otruyenapi.com
  request:
    delay-ms: 0
  batch:
    size: 5
    delay-ms: 0

google-drive:
  folder-id: 1H89l7BIVVNR3byETuuqZp2OXJpbSsT2R

jwt:
  expiration: 3600000 # 1 giờ
  refresh-expiration: 604800000 # 7 ngày
