server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: backend-comic

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
          from: ${MAIL_FROM}
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    protocol: smtp
    default-encoding: UTF-8

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# Cấu hình CORS
app:
  frontend-url: ${FRONTEND_URL}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:${FRONTEND_URL}}
  verification-token-expiration: 1800000 # 30p
  forgot-password-token-expiration: 1800000 # 30p
  backend-url: ${BACKEND_URL}

jwt:
  expiration: 3600000 # 1 giờ
  refresh-expiration: 604800000 # 7 ngày

b2:
  accessKeyId: ${B2_ACCESS_KEY_ID}
  secretKey: ${B2_API_KEY}
  endpoint: ${B2_END_POINT}
  region: ${B2_REGION}
  bucketName: ${B2_BUCKET_NAME}

# PayOS Configuration
payos:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}
  return-url: ${app.frontend-url}/payment/success
  cancel-url: ${app.frontend-url}/payment/failure

google:
  genai:
    api-key: ${GOOGLE_GENAI_API_KEY}
