services:
  # Frontend Next.js Application
  frontend-comic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-comic-app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api.webtoonnkt.click/api
      - NEXT_PUBLIC_OCR_BASE_URL=http://ocr-tts.webtoonnkt.click
      - NEXT_PUBLIC_OCR_API_KEY=BC6325CDCBDD891515C1FEE7D7CB9
    restart: no
    tmpfs:
      - /tmp
      - /var/tmp
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true

volumes:
  nginx_logs:
    driver: local
